spring:
  datasource:
    url: jdbc:h2:C:/Users/aldrm/Downloads/eatgo/data
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true


---
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  config:
    activate:
      on-profile: